In [2]:
# connect ke mysql

import mysql.connector


conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="dbkampus"
)

Data Mysql

In [3]:
# Ambil data dari SQL

import pandas as pd

query = "SELECT * FROM peserta_kelas"
df_mysql = pd.read_sql(query, conn)

print("Data dari MySQL:")
display(df_mysql.head())

Data dari MySQL:

C:\Users\USER\AppData\Local\Temp\ipykernel_24240\2951353079.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_mysql = pd.read_sql(query, conn)

   id         nim                      nama  angkatan prodi kode_kelas
0   1  0110221344                YUDIANSYAH      2021    TI  DM20252-P
1   2  0110224003  MUHAMMAD BINTANG GUNAWAN      2024    TI  DM20252-P
2   3  0110224004  MUHAMMAD SHOFIYYURROHMAN      2024    TI  DM20252-P
3   4  0110224009              ZAINAB AZNUR      2024    TI  DM20252-P
4   5  0110224012             ARYA NURYAWAN      2024    TI  DM20252-P

In [5]:
df_mysql.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          96 non-null     int64
 1   nim         96 non-null     object
 2   nama        96 non-null     object
 3   angkatan    96 non-null     int64
 4   prodi       96 non-null     object
 5   kode_kelas  96 non-null     object
dtypes: int64(2), object(4)
memory usage: 4.6+ KB

In [6]:
df_mysql.describe()

              id     angkatan
count  96.000000    96.000000
mean   48.500000  2023.968750
std    27.856777     0.306186
min     1.000000  2021.000000
25%    24.750000  2024.000000
50%    48.500000  2024.000000
75%    72.250000  2024.000000
max    96.000000  2024.000000

In [9]:
# Ambil data dari excel

df_excel = pd.read_excel("nilai_quiz.xlsx")

print("Data dari Excel:")
display(df_excel.head())

Data dari Excel:

,Last name,First name,Username,ID number,Email address,Mobile phone,State,Started on,Completed,Time taken,...,Q. 6 /6.67,Q. 7 /6.67,Q. 8 /6.67,Q. 9 /6.67,Q. 10 /6.67,Q. 11 /6.67,Q. 12 /6.67,Q. 13 /6.67,Q. 14 /6.67,Q. 15 /6.67
0,Robbani,Sholahuddin,0110224091,110224091.0,0110224091@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 1:12 PM,13 April 2026 1:20 PM,8 mins 20 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
1,Yahsya,Yurida,0110224100,110224100.0,0110224100@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 1:17 PM,13 April 2026 1:25 PM,8 mins 17 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
2,Amanda,Azkia,0110224099,110224099.0,0110224099@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 1:18 PM,13 April 2026 1:27 PM,9 mins 39 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
3,Hidayat,Rohmatul,0110224015,110224015.0,0110224015@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 1:18 PM,13 April 2026 1:26 PM,7 mins 46 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
4,Yudistira Ramdhany,Ahmad,0110224005,110224005.0,0110224005@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 1:22 PM,13 April 2026 1:31 PM,9 mins 27 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67

In [11]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Last name      41 non-null     object
 1   First name     40 non-null     object
 2   Username       40 non-null     object
 3   ID number      39 non-null     float64
 4   Email address  40 non-null     object
 5   Mobile phone   0 non-null      float64
 6   State          40 non-null     object
 7   Started on     40 non-null     object
 8   Completed      40 non-null     object
 9   Time taken     40 non-null     object
 10  Grade/100.00   41 non-null     float64
 11  Q. 1 /6.67     41 non-null     float64
 12  Q. 2 /6.67     41 non-null     float64
 13  Q. 3 /6.67     41 non-null     object
 14  Q. 4 /6.67     41 non-null     float64
 15  Q. 5 /6.67     41 non-null     float64
 16  Q. 6 /6.67     41 non-null     float64
 17  Q. 7 /6.67     41 non-null     float64
 18  Q. 8 /6.67     41 non-null     object
 19  Q. 9 /6.67     41 non-null     object
 20  Q. 10 /6.67    41 non-null     float64
 21  Q. 11 /6.67    41 non-null     float64
 22  Q. 12 /6.67    41 non-null     float64
 23  Q. 13 /6.67    41 non-null     float64
 24  Q. 14 /6.67    41 non-null     float64
 25  Q. 15 /6.67    41 non-null     float64
dtypes: float64(15), object(11)
memory usage: 8.5+ KB

In [12]:
df_excel = df_excel[['Last name', 'First name', 'ID number', 'Grade/100.00']]

In [13]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Last name     41 non-null     object
 1   First name    40 non-null     object
 2   ID number     39 non-null     float64
 3   Grade/100.00  41 non-null     float64
dtypes: float64(2), object(2)
memory usage: 1.4+ KB

Menangani Data yang Tidak Konsisten

In [16]:
print(df_mysql['nim'].head())
print(df_excel['ID number'].head())

0    0110221344
1    0110224003
2    0110224004
3    0110224009
4    0110224012
Name: nim, dtype: object
0    110224091.0
1    110224100.0
2    110224099.0
3    110224015.0
4    110224005.0
Name: ID number, dtype: float64

In [18]:
# Ubah ID number dijsdikan integer karena akan membuang angka decimal diakhir
df_excel['ID number'] = df_excel['ID number'].fillna(0).astype(int).astype(str)
df_excel.head()

# Tambahkan "0" didepan ID number : pola dari nim
df_excel['ID number'] = "0" + df_excel['ID number']
df_excel.head()

            Last name   First name   ID number  Grade/100.00
0             Robbani  Sholahuddin  0110224091         100.0
1              Yahsya       Yurida  0110224100         100.0
2              Amanda        Azkia  0110224099         100.0
3             Hidayat     Rohmatul  0110224015         100.0
4  Yudistira Ramdhany        Ahmad  0110224005         100.0

In [19]:
# Standdarisasi tipe data. Agar aman samakan tipe data nya dahulu, dari excel ID number

df_excel = df_excel.copy()
df_mysql = df_mysql.copy()

df_excel['ID number'] = df_excel['ID number'].astype(str)
df_mysql['nim'] = df_mysql['nim'].astype(str)

In [21]:
# Integrasi (penggabungan data)

df_integrasi = pd.merge(
    df_mysql,
    df_excel,
    left_on='nim',
    right_on='ID number',
    how='inner'
)

df_integrasi.head()

,id,nim,nama,angkatan,prodi,kode_kelas,Last name,First name,ID number,Grade/100.00
0,16,0110224049,IHSAN FIRDAUS,2024,TI,DM20252-P,Firman Syah,Lalu,0110224049,40.00
1,19,0110224065,NIKMA FITRI NURMALIA,2024,TI,DM20252-P,Wibowo,Latif,0110224065,53.33
2,24,0110224098,DANIL HELMI,2024,TI,DM20252-P,Solihin,Muhamad,0110224098,86.67
3,25,0110224100,CITRA SAKILA,2024,TI,DM20252-P,Yahsya,Yurida,0110224100,100.00
4,30,0110224125,MARDIYATIN,2024,TI,DM20252-P,Hayatu Suhaila,Nurul,0110224125,86.67

In [22]:
# buat dataframe agar lebih rapi
df_integrasi = df_integrasi[['Last name', 'First name', 'ID number', 'Grade/100.00']]

df_integrasi.head()

        Last name First name   ID number  Grade/100.00
0     Firman Syah       Lalu  0110224049         40.00
1          Wibowo      Latif  0110224065         53.33
2         Solihin    Muhamad  0110224098         86.67
3          Yahsya     Yurida  0110224100        100.00
4  Hayatu Suhaila      Nurul  0110224125         86.67

In [23]:
# renmae Grade/100.00 menjadi nilai

df_integrasi.rename(columns={'Grade/100.00': 'nilai'}, inplace=True)
df_integrasi.head()

        Last name First name   ID number   nilai
0     Firman Syah       Lalu  0110224049   40.00
1          Wibowo      Latif  0110224065   53.33
2         Solihin    Muhamad  0110224098   86.67
3          Yahsya     Yurida  0110224100  100.00
4  Hayatu Suhaila      Nurul  0110224125   86.67

In [24]:
df_integrasi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Last name   13 non-null     object
 1   First name  13 non-null     object
 2   ID number   13 non-null     object
 3   nilai       13 non-null     float64
dtypes: float64(1), object(3)
memory usage: 548.0+ bytes

In [29]:
# rename kolom 'First name' dan 'Last name' menjadi 'Nama lengkap'

df_integrasi['Nama lengkap'] = df_integrasi['First name'] + ' ' + df_integrasi['Last name']
df_integrasi.head()

        Last name First name         nim   nilai          Nama lengkap
0     Firman Syah       Lalu  0110224049   40.00      Lalu Firman Syah
1          Wibowo      Latif  0110224065   53.33          Latif Wibowo
2         Solihin    Muhamad  0110224098   86.67       Muhamad Solihin
3          Yahsya     Yurida  0110224100  100.00         Yurida Yahsya
4  Hayatu Suhaila      Nurul  0110224125   86.67  Nurul Hayatu Suhaila

In [26]:
# Rename kolom 'ID number' menjadi 'nim'
df_integrasi.rename(columns={'ID number': 'nim'}, inplace=True)
df_integrasi.head()

        Last name First name         nim   nilai          Nama lengkap
0     Firman Syah       Lalu  0110224049   40.00      Lalu Firman Syah
1          Wibowo      Latif  0110224065   53.33          Latif Wibowo
2         Solihin    Muhamad  0110224098   86.67       Muhamad Solihin
3          Yahsya     Yurida  0110224100  100.00         Yurida Yahsya
4  Hayatu Suhaila      Nurul  0110224125   86.67  Nurul Hayatu Suhaila

In [30]:
df_integrasi = df_integrasi[['Nama lengkap', 'nim', 'nilai']]
df_integrasi.head()

           Nama lengkap         nim   nilai
0      Lalu Firman Syah  0110224049   40.00
1          Latif Wibowo  0110224065   53.33
2       Muhamad Solihin  0110224098   86.67
3         Yurida Yahsya  0110224100  100.00
4  Nurul Hayatu Suhaila  0110224125   86.67